create table drivelite (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    name text,
    image_url text not null,
    inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);


alter table drivelite enable row level security;

create policy "Individuals can upload images." on drivelite for
    insert with check ((select auth.uid()) = user_id);

create policy "Individuals can view their own images. " on drivelite for
    select using ((select auth.uid()) = user_id);

create policy "Individuals can update their own images." on drivelite for
    update using ((select auth.uid()) = user_id);

create policy "Individuals can delete their own images." on drivelite for
    delete using ((select auth.uid()) = user_id);