create table markdowns (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  markdown text not null,
  is_completed bool not null,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);


alter table markdowns enable row level security;

create policy "Individuals can insert markdown" on markdowns for
    insert with check (auth.uid() = user_id);

create policy "Individuals can view markdown" on markdowns for
    select using (auth.uid() = user_id);

create policy "Individuals can update their own markdown." on markdowns for
    update using ( auth.uid() = user_id);

create policy "Individuals can delete their own markdown." on markdowns for
    delete using ( auth.uid() = user_id);